# Generated by Django 2.2 on 2022-06-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.BigIntegerField(blank=True, null=True)),
                ('isbn_id', models.CharField(blank=True, max_length=200, null=True)),
                ('authors', models.CharField(blank=True, max_length=200, null=True)),
                ('publication_year', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'library_book_details',
            },
        ),
    ]
