# Generated by Django 2.2 on 2022-06-23 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Libapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library_User_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.BigIntegerField(blank=True, null=True)),
                ('notify_me', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_one_v2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'library_user_details',
            },
        ),
    ]
