# Generated by Django 2.2 on 2022-06-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libapp', '0002_library_user_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='library_user_data',
            name='add_remove',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
