# Generated by Django 2.2 on 2022-06-23 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Libapp', '0004_library_staff_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library_Staff_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_flag', models.NullBooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_one_v4', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Library_Staff_information',
            },
        ),
    ]
