# Generated by Django 2.2 on 2022-06-23 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Libapp', '0005_library_staff_information'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='library_staff_information',
            table='library_staff_information',
        ),
    ]
