# Generated by Django 2.2 on 2022-06-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libapp', '0006_auto_20220623_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='library_data',
            name='amazon_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='library_data',
            name='amazon_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
